export * from './layout'
export * from './errorPage'
export * from './home/home'
export * from './accommodationsList/accommodationsList'
export * from './detailsAccommodation/detailsAccommodation'
export * from './about'